### Data Cleaning using numpy

**The following are the student marks of a class**
[44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,,122,92,np.nan,87,96,97,1,19,2,53, 44]



1. Find the no of outliers and missing values?
2. replace the outliers with 45 and missing value with 87.
3. what is the average marks of students after 2nd step?
4. How many students got less than 60 marks?
5. what is the maximum marks?
6. Convert the marks to float32.

### Solving Linear Equations


    
1. 2x + 3y - z = 10

    x - y + 2z = 5
    
    3x + 2y + z = 12
    
    
    
2. 2x + y - z + 3w = 8

    3x - 2y + 2z + 2w = 1
    
    x + 3y - 2z + w = 7
    
    4x - y + z - 2w = 3
   
   
   
3. 4x + 2y - 3z = 10

    -2x + 3y + z = -3
    
    x - y + 2z = 4
    
Solve the system of equations using NumPy's linalg.solve function.


### Conditional Selection with np.where()


1.	Generate a random 1D array A of 10 integers between 1 and 100.

2.	Use np.where() to find the indices where the elements of A are greater than 50.

3.	Create a new array B that contains elements from A where the condition is met.

4.	Calculate the mean of array B and print it along with arrays A and B.

### Replace Values with np.where()

1.	Create a 4x4 random integer matrix C with values between -10 and 10.

2.	Use np.where() to replace all negative values in matrix C with 0.

3.	Print the original matrix C and the modified matrix.

In [1]:
import numpy as np

In [2]:
mark=np.array([44,24,np.nan,59,32,96,188,52,62,58,52,120,np.nan,np.nan,3,56,81,59,122,92,np.nan,87,96,97,1,19,2,53,40])
mark

array([ 44.,  24.,  nan,  59.,  32.,  96., 188.,  52.,  62.,  58.,  52.,
       120.,  nan,  nan,   3.,  56.,  81.,  59., 122.,  92.,  nan,  87.,
        96.,  97.,   1.,  19.,   2.,  53.,  40.])

In [9]:
np.sum(np.isnan(mark))

0

In [10]:
outliers=(mark<0) | (mark>100)
np.sum(outliers)

3

In [11]:
mark=(np.where(np.isnan(mark),87,mark).astype('int16'))
mark

array([ 44,  24,  87,  59,  32,  96, 188,  52,  62,  58,  52, 120,  87,
        87,   3,  56,  81,  59, 122,  92,  87,  87,  96,  97,   1,  19,
         2,  53,  40], dtype=int16)

In [12]:
mark=(np.where(outliers,45,mark).astype('int16'))
mark

array([44, 24, 87, 59, 32, 96, 45, 52, 62, 58, 52, 45, 87, 87,  3, 56, 81,
       59, 45, 92, 87, 87, 96, 97,  1, 19,  2, 53, 40], dtype=int16)

In [14]:
average_mark=np.mean(mark)
average_mark

56.827586206896555

In [16]:
ess_60=np.sum(mark<60)
ess_60

18

In [17]:
max=np.max(mark)
max

97

In [18]:
mark.dtype

dtype('int16')

In [19]:
mark=mark.astype('float32')
mark.dtype

dtype('float32')

In [20]:
## 2

In [23]:
a=np.array([[2,3,-1],[1,-1,2],[3,2,1]])
b=np.array([10,5,12])
np.linalg.solve(a,b)

array([-7.36952666e+15,  7.36952666e+15,  7.36952666e+15])

In [26]:
c=np.array([[2,1,-1,3],[3,-2,2,2],[1,3,-2,1],[4,-1,1,-2]])
d=np.array([8,1,7,3])
np.linalg.solve(c,d)

array([ 1.73170732, -0.75609756, -3.46341463,  0.6097561 ])

In [28]:
e=np.array([[4,2,-3],[-2,3,1],[1,-1,2]])
f=np.array([10,-3,4])
np.linalg.solve(e,f)

array([2.85365854, 0.6097561 , 0.87804878])

In [29]:
## 3

In [30]:
import random

In [32]:
A=np.random.randint(1,100,10)
A

array([54,  3, 66, 11, 96, 72, 49, 54, 85, 51])

In [35]:
C=A[np.where(A>50)]
C

array([54, 66, 96, 72, 54, 85, 51])

In [36]:
B=C
B

array([54, 66, 96, 72, 54, 85, 51])

In [37]:
print(np.mean(B))
print(A)
print(B)

68.28571428571429
[54  3 66 11 96 72 49 54 85 51]
[54 66 96 72 54 85 51]


In [40]:
C=np.random.randint(-10,10,16).reshape(4,4)
C

array([[-9,  4, -2,  5],
       [ 0,  1,  5,  1],
       [ 6,  3,  6, -5],
       [ 1,  4, -8,  4]])

In [45]:
C=np.where(C<0,0,C)
C

array([[0, 4, 0, 5],
       [0, 1, 5, 1],
       [6, 3, 6, 0],
       [1, 4, 0, 4]])

In [46]:
print(f"Original matrix\n {C} \n \n Modified matrix \n {c}")

Original matrix
 [[0 4 0 5]
 [0 1 5 1]
 [6 3 6 0]
 [1 4 0 4]] 
 
 Modified matrix 
 [54 66 96 72 54 85 51]
