In [2]:
import numpy as np

1.Creating array in diff methods

In [3]:
arr=np.array([1,4,6,8,9,77])          ##method 1

In [4]:
arr

array([ 1,  4,  6,  8,  9, 77])

In [5]:
list1=[1,4,6,7,8]                    ##method 2
arr1=np.array(list1)
arr1

array([1, 4, 6, 7, 8])

In [6]:
tup=(2,6,8,4)
arr2=np.array(tup)
arr2                                ##method3

array([2, 6, 8, 4])

In [8]:
np.arange(1,7)                     ## method 4

array([1, 2, 3, 4, 5, 6])

In [9]:
np.linspace(33,55,)                ## method 5

array([33.        , 33.44897959, 33.89795918, 34.34693878, 34.79591837,
       35.24489796, 35.69387755, 36.14285714, 36.59183673, 37.04081633,
       37.48979592, 37.93877551, 38.3877551 , 38.83673469, 39.28571429,
       39.73469388, 40.18367347, 40.63265306, 41.08163265, 41.53061224,
       41.97959184, 42.42857143, 42.87755102, 43.32653061, 43.7755102 ,
       44.2244898 , 44.67346939, 45.12244898, 45.57142857, 46.02040816,
       46.46938776, 46.91836735, 47.36734694, 47.81632653, 48.26530612,
       48.71428571, 49.16326531, 49.6122449 , 50.06122449, 50.51020408,
       50.95918367, 51.40816327, 51.85714286, 52.30612245, 52.75510204,
       53.20408163, 53.65306122, 54.10204082, 54.55102041, 55.        ])

1D NumPy Array for 12 positive int

In [12]:
arra=np.arange(1,13)

In [13]:
arra

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

1D NumPy Array for 20 elements between 0 and 12

In [14]:
arra1=np.linspace(0,12,20)
arra1

array([ 0.        ,  0.63157895,  1.26315789,  1.89473684,  2.52631579,
        3.15789474,  3.78947368,  4.42105263,  5.05263158,  5.68421053,
        6.31578947,  6.94736842,  7.57894737,  8.21052632,  8.84210526,
        9.47368421, 10.10526316, 10.73684211, 11.36842105, 12.        ])

Attributes of Arra

In [15]:
arra.dtype

dtype('int32')

In [16]:
arra.size

12

In [18]:
arra.nbytes

48

In [19]:
arra.itemsize

4

In [20]:
arra.ndim

1

Attributes of Arra1

In [21]:
arra1.size

20

In [22]:
arra1.itemsize

8

In [24]:
arra1.ndim

1

In [25]:
arra1.nbytes

160

In [26]:
arra1.dtype

dtype('float64')

Statistics method

arra

In [27]:
np.mean(arra)

6.5

In [28]:
np.median(arra)

6.5

In [29]:
np.min(arra)

1

In [30]:
np.max(arra)

12

In [33]:
np.max(arra)-np.min(arra)                ##range

11

In [34]:
np.var(arra)

11.916666666666666

In [36]:
np.std(arra)

3.452052529534663

arra1

In [37]:
np.mean(arra1)

5.999999999999999

In [39]:
np.median(arra1)

6.0

In [40]:
np.max(arra1)

12.0

In [41]:
np.min(arra1)

0.0

In [42]:
np.max(arra1)-np.min(arra1)

12.0

In [43]:
np.var(arra1)

13.26315789473684

In [44]:
np.std(arra1)

3.6418618720013036

IQR for Arra

In [45]:
Q1=np.percentile(arra,25)
Q1

3.75

In [49]:
Q3=np.percentile(arra,75)

In [50]:
Q3

9.25

In [51]:
IQR=Q3-Q1

In [52]:
IQR

5.5

In [53]:
lower=Q1 - (1.5*IQR)
lower                                   ##lower limt

-4.5

In [55]:
upper=Q3+(1.5*IQR)                    ##upper limt
upper

17.5

IQR for Arra1

In [56]:
Q1=np.percentile(arra1,25)
Q1

3.0

In [58]:
Q3=np.percentile(arra1,75)
Q3

9.0

In [59]:
IQR=Q3-Q1

In [60]:
IQR

6.0

In [61]:
lower = Q1- (1.5*IQR)
lower

-6.0

In [64]:
upper=Q3+(1.5*IQR)
upper

18.0